name = "cosmic-protocol-worker"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "PLANET_DO"
class_name = "PlanetDO"

[[migrations]]
tag = "v1"
new_classes = ["PlanetDO"]

[[d1_databases]]
binding = "DB"
database_name = "og-game"
database_id = "local"

[[kv_namespaces]]
binding = "KV"
id = "local"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2"
bucket_name = "cosmic-protocol-assets"

[[triggers.crons]]
cron = "*/1 * * * *"
